// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { unified } from '@astrojs/markdown-remark';
import rehypeMermaid from 'rehype-mermaid';
import { heliaStarlight } from '@ambiqai/helia-ui/starlight';
import redirects from './src/data/redirects.json' with { type: 'json' };
/* Generated by `npm run prepare:docs` and committed, so the nav is reviewable
 * in the diff. pyref hands back one group object; Starlight wants an array. */
import apiSidebar from './src/generated/api-sidebar.json' with { type: 'json' };
/* Also generated and committed: the command-line group, then the two pages
 * that sit beside it. An array rather than one group, because the check that
 * asserts every generated route is claimed reads this same file. */
import cliSidebar from './src/generated/cli-sidebar.json' with { type: 'json' };
import { sourceRefArtifacts } from './src/integrations/source-ref.mjs';

const site = 'https://ambiqai.github.io';
const base = '/helia-profiler';
const basePath = `${base}/`;

export default defineConfig({
  site,
  base,
  /* Legacy MkDocs routes. `served` entries are already real pages at the same
   * path, so they must stay out of this map or Astro sees a route collision. */
  /* `redirects` covers the legacy MkDocs routes (checked against the fixture);
     `moved` covers routes this site published and later moved. */
  redirects: { ...redirects.redirects, ...(redirects.moved ?? {}) },
  /* Diagrams are rendered to SVG at build time by a headless Chromium, so a
   * reader needs no client JS and the page needs no layout shift. The browser
   * is installed by the docs workflow; without it the build fails loudly. */
  markdown: {
    processor: unified({
      rehypePlugins: [[rehypeMermaid, { strategy: 'inline-svg' }]],
    }),
  },
  integrations: [
    starlight({
      title: 'heliaPROFILER',
      description:
        'Profile LiteRT and ExecuTorch models on Ambiq Apollo hardware.',
      favicon: '/heliaprofiler-icon.png',
      /* This site ships its own 404 at src/pages/404.astro, outside the docs
       * collection so the discoverability integration does not index a route
       * nobody serves. Starlight injects a static /404 of its own, and two
       * routes at one path is a hard error in a coming Astro. */
      disable404Route: true,
      /* Opt-in: it paints the build-time mermaid SVGs from the token set. */
      customCss: ['@ambiqai/helia-ui/mermaid.css', './src/styles/block-diagram.css'],
      plugins: [
        heliaStarlight({
          accent: 'helia-profiler',
          sidebar: 'always',
          header: {
            title: 'heliaPROFILER',
            hub: {
              label: 'HELIA',
              href: 'https://ambiqai.github.io/helia-developer-hub/',
            },
          },
          sections: [
            { label: 'Home', href: basePath, sidebar: false },
            {
              label: 'Getting started',
              href: `${basePath}getting-started/`,
              sidebar: [
                { label: 'Overview', slug: 'getting-started' },
                { label: 'Install', slug: 'getting-started/install' },
                { label: 'Hardware prerequisites', slug: 'getting-started/hardware-prerequisites' },
                { label: 'Validate your setup', slug: 'getting-started/validate-your-setup' },
                { label: 'First profile', slug: 'getting-started/first-profile' },
                { label: 'Configure a run', slug: 'getting-started/configure-a-run' },
                { label: 'Where next', slug: 'getting-started/where-next' },
              ],
            },
            {
              label: 'User guide',
              href: `${basePath}guide/`,
              sidebar: [
                { label: 'Overview', slug: 'guide' },
                {
                  label: 'Set up a run',
                  items: [
                    { label: 'Engines', slug: 'guide/engines' },
                    { label: 'Models', slug: 'guide/models' },
                    { label: 'Boards and targets', slug: 'guide/boards' },
                    { label: 'Toolchains', slug: 'guide/toolchains' },
                    { label: 'Capture transports', slug: 'guide/transports' },
                    { label: 'Memory placement', slug: 'guide/memory' },
                    { label: 'ExecuTorch NS kernels', slug: 'guide/executorch-ns-kernels' },
                    { label: 'Configuration', slug: 'guide/configuration' },
                  ],
                },
                {
                  label: 'Measure',
                  items: [
                    { label: 'PMU Counters', slug: 'guide/pmu-counters' },
                    { label: 'Power Measurement', slug: 'guide/power' },
                  ],
                },
                {
                  label: 'Read results',
                  items: [
                    { label: 'Output & Results', slug: 'guide/output' },
                    {
                      label: 'Analysis & Run Comparison',
                      slug: 'guide/analysis-comparison',
                    },
                    {
                      label: 'Model Explorer Overlays',
                      slug: 'guide/model-explorer',
                    },
                  ],
                },
                {
                  label: 'Concepts',
                  items: [
                    { label: 'Overview', slug: 'guide/concepts' },
                    { label: 'Pipeline & Stages', slug: 'guide/concepts/pipeline' },
                    {
                      label: 'Engine Adapters',
                      slug: 'guide/concepts/engine-adapters',
                    },
                    {
                      label: 'Firmware Generation',
                      slug: 'guide/concepts/firmware',
                    },
                    { label: 'Data Capture', slug: 'guide/concepts/capture' },
                    {
                      label: 'Field Diagnostics',
                      slug: 'guide/concepts/field-diagnostics',
                    },
                    {
                      label: 'Contributing an Engine',
                      slug: 'guide/concepts/adding-an-engine',
                    },
                  ],
                },
              ],
            },
            {
              label: 'Examples',
              href: `${basePath}examples/`,
              sidebar: [
                { label: 'Overview', slug: 'examples' },
                {
                  label: 'Interactive Python',
                  slug: 'examples/interactive-python',
                },
                { label: 'Basic Profiling', slug: 'examples/basic-profiling' },
                {
                  label: 'Atomiq110 NPU Profiling (Experimental)',
                  slug: 'examples/atomiq110-npu-profiling',
                },
                {
                  label: 'Vanilla TFLM Baseline',
                  slug: 'examples/tflm-baseline',
                },
                { label: 'Per-Layer Breakdown', slug: 'examples/per-layer' },
                {
                  label: 'Engine Comparison',
                  slug: 'examples/engine-comparison',
                },
                {
                  label: 'Toolchain Comparison',
                  slug: 'examples/toolchain-comparison',
                },
                { label: 'Power Profiling', slug: 'examples/power-profiling' },
              ],
            },
            {
              label: 'Reference',
              href: `${basePath}reference/`,
              sidebar: [
                { label: 'Overview', slug: 'reference' },
                apiSidebar,
                ...cliSidebar,
                {
                  label: 'Compatibility Baseline',
                  slug: 'reference/compatibility-baseline',
                },
                { label: 'Wire Protocol', slug: 'reference/wire-protocol' },
              ],
            },
          ],
          discoverability: {
            ogImage: true,
            jsonLd: true,
            markdown: true,
            llms: true,
          },
          footer: {
            links: [
              { label: 'Getting started', href: `${basePath}getting-started/` },
              { label: 'User guide', href: `${basePath}guide/` },
              { label: 'Examples', href: `${basePath}examples/` },
              { label: 'Reference', href: `${basePath}reference/` },
              {
                label: 'GitHub',
                href: 'https://github.com/AmbiqAI/helia-profiler',
              },
            ],
            tagline: 'Part of the Ambiq HELIA developer ecosystem.',
            logo: 'ambiq',
          },
        }),
      ],
    }),
    /* Last on purpose: it rewrites what the integrations above write. */
    sourceRefArtifacts(),
  ],
});
