// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { heliaStarlight } from '@ambiqai/helia-ui/starlight';
import redirects from './src/data/redirects.json' with { type: 'json' };
/* Generated by `npm run prepare:docs` and committed, so the nav is reviewable
 * in the diff. pyref hands back one group object; Starlight wants an array. */
import apiSidebar from './src/generated/api-sidebar.json' with { type: 'json' };
/* Also generated and committed: the command-line group, then the two pages
 * that sit beside it. An array rather than one group, because the check that
 * asserts every generated route is claimed reads this same file. */
import cliSidebar from './src/generated/cli-sidebar.json' with { type: 'json' };
import { sourceRefArtifacts } from './src/integrations/source-ref.mjs';

const site = 'https://ambiqai.github.io';
const base = '/helia-profiler';
const basePath = `${base}/`;

export default defineConfig({
  site,
  base,
  /* Legacy MkDocs routes. `served` entries are already real pages at the same
   * path, so they must stay out of this map or Astro sees a route collision. */
  /* `redirects` covers the legacy MkDocs routes (checked against the fixture);
     `moved` covers routes this site published and later moved. */
  redirects: { ...redirects.redirects, ...(redirects.moved ?? {}) },
  integrations: [
    starlight({
      title: 'heliaPROFILER',
      description:
        'Profile LiteRT and ExecuTorch models on Ambiq Apollo hardware.',
      favicon: '/heliaprofiler-icon.png',
      /* This site ships its own 404 at src/pages/404.astro, outside the docs
       * collection so the discoverability integration does not index a route
       * nobody serves. Starlight injects a static /404 of its own, and two
       * routes at one path is a hard error in a coming Astro. */
      disable404Route: true,
      plugins: [
        heliaStarlight({
          accent: 'helia-profiler',
          sidebar: 'always',
          header: {
            title: 'heliaPROFILER',
            hub: {
              label: 'HELIA',
              href: 'https://ambiqai.github.io/helia-developer-hub/',
            },
          },
          sections: [
            { label: 'Home', href: basePath, sidebar: false },
            {
              label: 'Getting started',
              href: `${basePath}getting-started/`,
              sidebar: [
                { label: 'Overview', slug: 'getting-started' },
                { label: 'Install', slug: 'getting-started/install' },
                { label: 'Hardware prerequisites', slug: 'getting-started/hardware-prerequisites' },
                { label: 'Validate your setup', slug: 'getting-started/validate-your-setup' },
                { label: 'First profile', slug: 'getting-started/first-profile' },
                { label: 'Configure a run', slug: 'getting-started/configure-a-run' },
                { label: 'Where next', slug: 'getting-started/where-next' },
              ],
            },
            {
              label: 'User guide',
              href: `${basePath}guide/`,
              sidebar: [
                { label: 'Overview', slug: 'guide' },
                {
                  label: 'Set up a run',
                  items: [
                    { label: 'Engines', slug: 'guide/engines' },
                    { label: 'Models', slug: 'guide/models' },
                    { label: 'Boards and targets', slug: 'guide/boards' },
                    { label: 'Toolchains', slug: 'guide/toolchains' },
                    { label: 'Capture transports', slug: 'guide/transports' },
                    { label: 'Memory placement', slug: 'guide/memory' },
                    { label: 'ExecuTorch NS kernels', slug: 'guide/executorch-ns-kernels' },
                    { label: 'Configuration', slug: 'guide/configuration' },
                  ],
                },
                {
                  label: 'Measure',
                  items: [
                    { label: 'PMU counters', slug: 'guide/pmu-counters' },
                    { label: 'Power measurement', slug: 'guide/power' },
                    { label: 'Joulescope setup and wiring', slug: 'guide/power-joulescope' },
                    { label: 'INA228 on the target', slug: 'guide/power-ina228' },
                    { label: 'Windows and the clean window', slug: 'guide/power-windows' },
                    { label: 'Verifying a capture', slug: 'guide/power-verify' },
                  ],
                },
                {
                  label: 'Read results',
                  items: [
                    { label: 'Output files', slug: 'guide/output' },
                    { label: 'Latency and per-layer', slug: 'guide/latency' },
                    { label: 'Analysis and comparison', slug: 'guide/analysis-comparison' },
                    { label: 'Model Explorer overlays', slug: 'guide/model-explorer' },
                    { label: 'Parsing outputs', slug: 'guide/parsing-outputs' },
                    { label: 'Troubleshooting', slug: 'guide/troubleshooting' },
                  ],
                },
                {
                  label: 'Concepts',
                  items: [
                    { label: 'Overview', slug: 'guide/concepts' },
                    { label: 'Pipeline', slug: 'guide/concepts/pipeline' },
                    {
                      label: 'Engine adapters',
                      slug: 'guide/concepts/engine-adapters',
                    },
                    {
                      label: 'Firmware generation',
                      slug: 'guide/concepts/firmware',
                    },
                    { label: 'Data capture', slug: 'guide/concepts/capture' },
                    {
                      label: 'Field diagnostics',
                      slug: 'guide/concepts/field-diagnostics',
                    },
                    {
                      label: 'Adding an engine',
                      slug: 'guide/concepts/adding-an-engine',
                    },
                  ],
                },
              ],
            },
            {
              label: 'Examples',
              href: `${basePath}examples/`,
              sidebar: [
                { label: 'Overview', slug: 'examples' },
                { label: 'Profile a model', slug: 'examples/basic-profiling' },
                { label: 'Every counter, every layer', slug: 'examples/per-layer' },
                { label: 'Vanilla TFLM baseline', slug: 'examples/tflm-baseline' },
                { label: 'Compare engines', slug: 'examples/engine-comparison' },
                { label: 'Compare toolchains', slug: 'examples/toolchain-comparison' },
                { label: 'Power capture', slug: 'examples/power-profiling' },
                { label: 'Atomiq110 NPU (experimental)', slug: 'examples/atomiq110-npu-profiling' },
                { label: 'Interactive Python', slug: 'examples/interactive-python' },
                { label: 'Batch runs from YAML', slug: 'examples/batch-runs' },
                { label: 'Re-analyse saved results', slug: 'examples/reanalyse-results' },
                { label: 'Model Explorer overlay', slug: 'examples/model-explorer-overlay' },
                { label: 'Read a power summary', slug: 'examples/power-read-summary' },
                { label: 'Compare two power runs', slug: 'examples/power-compare' },
              ],
            },
            {
              label: 'Reference',
              href: `${basePath}reference/`,
              sidebar: [
                { label: 'Overview', slug: 'reference' },
                apiSidebar,
                ...cliSidebar,
                {
                  label: 'Compatibility Baseline',
                  slug: 'reference/compatibility-baseline',
                },
                { label: 'Compatibility table', slug: 'reference/compatibility' },
                { label: 'Wire Protocol', slug: 'reference/wire-protocol' },
              ],
            },
          ],
          discoverability: {
            ogImage: true,
            jsonLd: true,
            markdown: true,
            llms: true,
          },
          footer: {
            links: [
              { label: 'Getting started', href: `${basePath}getting-started/` },
              { label: 'User guide', href: `${basePath}guide/` },
              { label: 'Examples', href: `${basePath}examples/` },
              { label: 'Reference', href: `${basePath}reference/` },
              {
                label: 'GitHub',
                href: 'https://github.com/AmbiqAI/helia-profiler',
              },
            ],
            tagline: 'Part of the Ambiq HELIA developer ecosystem.',
            logo: 'ambiq',
          },
        }),
      ],
    }),
    /* Last on purpose: it rewrites what the integrations above write. */
    sourceRefArtifacts(),
  ],
});
