// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { heliaStarlight } from '@ambiqai/helia-ui/starlight';
import redirects from './src/data/redirects.json' with { type: 'json' };
/* Generated by `npm run prepare:docs` and committed, so the nav is reviewable
 * in the diff. pyref hands back one group object; Starlight wants an array. */
import apiSidebar from './src/generated/api-sidebar.json' with { type: 'json' };
/* Also generated and committed: the command-line group, then the two pages
 * that sit beside it. An array rather than one group, because the check that
 * asserts every generated route is claimed reads this same file. */
import cliSidebar from './src/generated/cli-sidebar.json' with { type: 'json' };
import { sourceRefArtifacts } from './src/integrations/source-ref.mjs';

const site = 'https://ambiqai.github.io';
const base = '/helia-profiler';
const basePath = `${base}/`;

export default defineConfig({
  site,
  base,
  /* Legacy MkDocs routes. `served` entries are already real pages at the same
   * path, so they must stay out of this map or Astro sees a route collision. */
  redirects: redirects.redirects,
  integrations: [
    starlight({
      title: 'heliaPROFILER',
      description:
        'Profile LiteRT and ExecuTorch models on Ambiq Apollo hardware.',
      favicon: '/heliaprofiler-icon.png',
      /* This site ships its own 404 at src/pages/404.astro, outside the docs
       * collection so the discoverability integration does not index a route
       * nobody serves. Starlight injects a static /404 of its own, and two
       * routes at one path is a hard error in a coming Astro. */
      disable404Route: true,
      plugins: [
        heliaStarlight({
          accent: 'helia-profiler',
          sidebar: 'always',
          header: {
            title: 'heliaPROFILER',
            hub: {
              label: 'HELIA',
              href: 'https://ambiqai.github.io/helia-developer-hub/',
            },
          },
          sections: [
            { label: 'Home', href: basePath, sidebar: false },
            {
              label: 'Getting started',
              href: `${basePath}getting-started/`,
              sidebar: [{ label: 'Overview', slug: 'getting-started' }],
            },
            {
              label: 'User guide',
              href: `${basePath}guide/`,
              sidebar: [{ label: 'Overview', slug: 'guide' }],
            },
            {
              label: 'Examples',
              href: `${basePath}examples/`,
              sidebar: [{ label: 'Overview', slug: 'examples' }],
            },
            {
              label: 'Reference',
              href: `${basePath}reference/`,
              sidebar: [
                { label: 'Overview', slug: 'reference' },
                apiSidebar,
                ...cliSidebar,
              ],
            },
          ],
          discoverability: {
            ogImage: true,
            jsonLd: true,
            markdown: true,
            llms: true,
          },
          footer: {
            links: [
              { label: 'Getting started', href: `${basePath}getting-started/` },
              { label: 'User guide', href: `${basePath}guide/` },
              { label: 'Examples', href: `${basePath}examples/` },
              { label: 'Reference', href: `${basePath}reference/` },
              {
                label: 'GitHub',
                href: 'https://github.com/AmbiqAI/helia-profiler',
              },
            ],
            tagline: 'Part of the Ambiq HELIA developer ecosystem.',
            logo: 'ambiq',
          },
        }),
      ],
    }),
    /* Last on purpose: it rewrites what the integrations above write. */
    sourceRefArtifacts(),
  ],
});
