"""heliaRT NSX wrapper generation.

heliaRT ships a native ``nsx/`` CMake module in its distributions, but that
native module is either source-build-only (requires the full repo) or needs
a thin wrapper to expose the prebuilt static library as ``nsx::helia_rt``.
This module generates the temporary ``nsx-module.yaml`` + ``CMakeLists.txt``
wrapper (and a nested shim copy) that HPX installs under
``work_dir/modules/helia-rt/`` for each profiler run.  This shim is retired
once heliaRT ships a native ``nsx-module.yaml`` compatible with both build
modes directly.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

from ...errors import EngineError
from .artifacts import HELIART_MIN_VERSION, _DIST_DIRS

log = logging.getLogger("hpx")


def _install_nsx_module(
    module_dir: Path,
    dist_path: Path,
    *,
    variant: str,
    core_override: str | None = None,
) -> None:
    """Install the NSX module files and distribution content into *module_dir*.

    Requires the distribution to ship ``nsx/nsx-module.yaml``
    (heliaRT >= 1.16.0).  The upstream ``nsx/CMakeLists.txt`` is a
    source-build module and cannot be used with the prebuilt dist alone
    (it requires the full repo with ``cmake/helia_rt_sources.cmake``).
    HPX generates a minimal prebuilt-wrapper CMakeLists.txt instead.
    """
    nsx_dir = dist_path / "nsx"
    src_yaml = nsx_dir / "nsx-module.yaml"
    if not src_yaml.is_file():
        raise EngineError(
            f"heliaRT distribution at {dist_path} is missing nsx/nsx-module.yaml",
            hint=(f"Expected nsx/nsx-module.yaml. Use heliaRT >= v{HELIART_MIN_VERSION}."),
        )

    shutil.copy2(src_yaml, module_dir / "nsx-module.yaml")

    # --- Generate a prebuilt-wrapper CMakeLists.txt ---
    # v1.16.0's nsx/CMakeLists.txt is a source-build module that requires
    # the full heliaRT repo.  For the prebuilt dist, we generate a simpler
    # wrapper that links the static library directly.
    core_override_block = ""
    if core_override:
        tag = core_override.lower()
        core_override_block = (
            f'\n# core_override: force {tag} library\nset(_HELIA_RT_CORE "{tag}")\n'
        )

    cmake_text = _PREBUILT_CMAKE_TEMPLATE.format(
        variant=variant,
        core_override_block=core_override_block,
    )
    (module_dir / "CMakeLists.txt").write_text(cmake_text)

    # --- Copy distribution content (lib/, tensorflow/, third_party/, …) ---
    for d in _DIST_DIRS:
        target = module_dir / d
        source = dist_path / d
        if target.is_dir():
            shutil.rmtree(target)
        if source.is_dir():
            shutil.copytree(source, target)
            log.debug("Copied %s → %s", source, target)

    _write_nested_nsx_shim(module_dir)


def _write_nested_nsx_shim(module_dir: Path) -> None:
    """Mirror the generated wrapper under ``nsx/`` for NSX local-module loads.

    NSX's lock/sync flow records the native heliaRT metadata path as
    ``modules/helia-rt/nsx``.  Provide a tiny shim there that delegates back
    to the generated root wrapper so add_subdirectory() can load the module.
    """
    nsx_dir = module_dir / "nsx"
    if nsx_dir.is_dir():
        shutil.rmtree(nsx_dir)
    nsx_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(module_dir / "nsx-module.yaml", nsx_dir / "nsx-module.yaml")
    (nsx_dir / "CMakeLists.txt").write_text(
        "# Auto-generated by hpx HeliaRTAdapter (NSX shim).\n"
        "# Do not edit — regenerated on every hpx run.\n"
        "cmake_minimum_required(VERSION 3.21)\n"
        "\n"
        "include(\"${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt\")\n"
    )


# Prebuilt wrapper template for heliaRT >= v1.16.0 distributions.
# The dist's own nsx/CMakeLists.txt is source-build-only; this provides a
# minimal prebuilt-style module that links the static .a library.
_PREBUILT_CMAKE_TEMPLATE = """\
# Auto-generated by hpx HeliaRTAdapter (prebuilt mode).
# Do not edit — regenerated on every hpx run.
cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED NSX_BOARD_FLAGS_TARGET)
    message(FATAL_ERROR
        "nsx-helia-rt: NSX_BOARD_FLAGS_TARGET must be defined.")
endif()

if(NOT DEFINED NSX_SOC_FAMILY)
    message(FATAL_ERROR
        "nsx-helia-rt: NSX_SOC_FAMILY must be defined.")
endif()

# --- Resolve Cortex-M core tag from SoC family ---
set(_HELIA_RT_CORE "")
if(NSX_SOC_FAMILY MATCHES "^apollo5|^apollo330|^apollo510|^atomiq")
    set(_HELIA_RT_CORE "cm55")
elseif(NSX_SOC_FAMILY MATCHES "^apollo4|^apollo3")
    set(_HELIA_RT_CORE "cm4")
else()
    message(FATAL_ERROR
        "nsx-helia-rt: unsupported NSX_SOC_FAMILY '${{NSX_SOC_FAMILY}}'")
endif()
{core_override_block}
# --- Resolve toolchain tag ---
set(_HELIA_RT_TOOLCHAIN "gcc")
if(CMAKE_C_COMPILER_ID STREQUAL "ARMClang" OR
   CMAKE_C_COMPILER MATCHES "armclang")
    set(_HELIA_RT_TOOLCHAIN "armclang")
elseif(CMAKE_C_COMPILER MATCHES "atfe")
    set(_HELIA_RT_TOOLCHAIN "atfe")
endif()

# --- Build variant ---
set(HELIA_RT_VARIANT "{variant}" CACHE STRING
    "heliaRT build variant" FORCE)

# --- Locate the prebuilt static library ---
set(_HELIA_RT_LIB_NAME
    "libhelia-rt-${{_HELIA_RT_CORE}}-${{_HELIA_RT_TOOLCHAIN}}-${{HELIA_RT_VARIANT}}.a")
set(_HELIA_RT_LIB_PATH
    "${{CMAKE_CURRENT_LIST_DIR}}/lib/${{_HELIA_RT_LIB_NAME}}")

if(NOT EXISTS "${{_HELIA_RT_LIB_PATH}}")
    message(FATAL_ERROR
        "nsx-helia-rt: prebuilt library not found:\\n"
        "  ${{_HELIA_RT_LIB_PATH}}\\n"
        "Check HELIA_RT_VARIANT (${{HELIA_RT_VARIANT}}) and "
        "toolchain (${{_HELIA_RT_TOOLCHAIN}}).")
endif()

message(STATUS "nsx-helia-rt: using ${{_HELIA_RT_LIB_NAME}}")

# --- Import the prebuilt static library ---
add_library(nsx_helia_rt_prebuilt STATIC IMPORTED GLOBAL)
set_target_properties(nsx_helia_rt_prebuilt PROPERTIES
    IMPORTED_LOCATION "${{_HELIA_RT_LIB_PATH}}"
)

# --- Platform glue (MicroPrintf + debug_log) ---
add_library(nsx_helia_rt STATIC
    ${{CMAKE_CURRENT_LIST_DIR}}/tensorflow/lite/micro/micro_log.cc
    ${{CMAKE_CURRENT_LIST_DIR}}/tensorflow/lite/micro/cortex_m_generic/debug_log.cc
)
set_target_properties(nsx_helia_rt PROPERTIES EXPORT_NAME helia_rt)
add_library(nsx::helia_rt ALIAS nsx_helia_rt)

target_link_libraries(nsx_helia_rt
    PUBLIC
        ${{NSX_BOARD_FLAGS_TARGET}}
        nsx_helia_rt_prebuilt
    PRIVATE
        nsx_soc_hal
        nsx_core
)

target_include_directories(nsx_helia_rt
    PUBLIC
        $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}>
        $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party>
        $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party/flatbuffers/include>
        $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party/gemmlowp>
)

target_compile_definitions(nsx_helia_rt
    PUBLIC
        TF_LITE_STATIC_MEMORY
        NS_TFSTRUCTURE_RECENT
        NS_TFLM_NEW_MICRO_PROFILER
)
"""


def _install_nsx_module_source(
    module_dir: Path,
    source_path: Path,
    *,
    variant: str,
) -> None:
    """Install a source-build NSX module wrapper at *module_dir*.

    Writes a minimal ``CMakeLists.txt`` that includes the heliaRT source
    tree's own ``nsx/CMakeLists.txt`` while pointing ``HELIA_RT_TFLM_ROOT``
    at the user-supplied heliaRT checkout.
    """
    # Wipe any prior install (e.g. switching modes inside one work_dir).
    for d in (*_DIST_DIRS, "lib", "nsx", "_source_shim"):
        tgt = module_dir / d
        if tgt.is_dir():
            shutil.rmtree(tgt)

    nsx_cmake = source_path / "nsx" / "CMakeLists.txt"

    cmake_text = (
        "# Auto-generated by hpx HeliaRTAdapter (source-build mode).\n"
        "# Do not edit — regenerated on every hpx run.\n"
        "cmake_minimum_required(VERSION 3.21)\n"
        "\n"
        f'set(HELIA_RT_VARIANT "{variant}" '
        'CACHE STRING "heliaRT build variant" FORCE)\n'
        f'set(HELIA_RT_TFLM_ROOT "{source_path.as_posix()}" '
        'CACHE PATH "heliaRT repo root" FORCE)\n'
        "\n"
        "# Delegate to the source-build NSX module that ships with the\n"
        "# heliaRT repo while overriding HELIA_RT_TFLM_ROOT to the user\n"
        "# supplied source checkout.\n"
        f'include("{nsx_cmake.as_posix()}")\n'
    )
    (module_dir / "CMakeLists.txt").write_text(cmake_text)

    shutil.copy2(
        source_path / "nsx" / "nsx-module.yaml",
        module_dir / "nsx-module.yaml",
    )
    _write_nested_nsx_shim(module_dir)
