"""Firmware generation — NSX app scaffolding for the profiler.

This module provides the interface between the pipeline stages and the
low-level firmware template rendering + NSX build system.  Each function
receives a ``PipelineContext`` and operates on the fields set by prior stages.
"""

from __future__ import annotations

import glob
import logging
import shutil
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from ..errors import BuildError, FirmwareError

if TYPE_CHECKING:
    from ..pipeline import PipelineContext

log = logging.getLogger("hpx")

# ---------------------------------------------------------------------------
# SDK tier → module set mapping
# ---------------------------------------------------------------------------
_SDK_MODULES: dict[str, list[str]] = {
    "r3": [
        "nsx-ambiqsuite-r3",
        "nsx-ambiq-hal-r3",
        "nsx-ambiq-bsp-r3",
    ],
    "r4": [
        "nsx-ambiqsuite-r4",
        "nsx-ambiq-hal-r4",
        "nsx-ambiq-bsp-r4",
    ],
    "r5": [
        "nsx-ambiqsuite-r5",
        "nsx-ambiq-hal-r5",
        "nsx-ambiq-bsp-r5",
    ],
}

# Common modules every profiler app needs (order matters for CMake)
_COMMON_MODULES = [
    "nsx-soc-hal",
    "nsx-cmsis-startup",
    # board module inserted dynamically
    "nsx-core",
    "nsx-harness",
    "nsx-utils",
    "nsx-power",
    "nsx-perf",
    "nsx-pmu-armv8m",
    "nsx-tooling",
]


def _board_module_name(board: str) -> str:
    """Derive the NSX board module name from a board name."""
    return f"nsx-board-{board.replace('_', '-')}"


def _resolve_module_list(board: str, sdk_tier: str) -> list[str]:
    """Build the ordered module list for a profiler app."""
    sdk_mods = _SDK_MODULES.get(sdk_tier)
    if sdk_mods is None:
        raise FirmwareError(
            f"Unknown SDK tier '{sdk_tier}'",
            hint=f"Known tiers: {', '.join(_SDK_MODULES)}",
        )
    modules = list(sdk_mods)
    board_mod = _board_module_name(board)
    # Insert board + common modules after SDK modules
    for mod in _COMMON_MODULES:
        if mod == "nsx-soc-hal":
            modules.append(mod)
            modules.append("nsx-cmsis-startup")
            modules.append(board_mod)
        elif mod in ("nsx-cmsis-startup",):
            continue  # already added above
        else:
            modules.append(mod)
    return modules


# ---------------------------------------------------------------------------
# PMU preset mapping (hpx preset name → C enum)
# ---------------------------------------------------------------------------
_PMU_PRESET_MAP: dict[str, str] = {
    "basic_cpu": "NS_PMU_PRESET_BASIC_CPU",
    "memory": "NS_PMU_PRESET_MEMORY",
    "mve": "NS_PMU_PRESET_MVE",
    "ml_default": "NS_PMU_PRESET_ML_DEFAULT",
}


# ---------------------------------------------------------------------------
# Template strings for the generated firmware app
# ---------------------------------------------------------------------------

_NSX_YML_TEMPLATE = """\
schema_version: 1
project:
  name: hpx_profiler
target:
  board: {board}
  soc: {soc}
toolchain: {toolchain}
channel: stable
profile: {board}_minimal
profile_status: active
modules:
{module_entries}
features: {{}}
module_registry:
  projects: {{}}
  modules: {{}}
"""

_MODULES_CMAKE_TEMPLATE = """\
# Auto-generated by heliaPROFILER — do not edit.
set(NSX_APP_MODULES
{module_list}
)
"""

_CMAKELISTS_TEMPLATE = """\
# Auto-generated by heliaPROFILER — do not edit.
cmake_minimum_required(VERSION 3.24)
project(hpx_profiler LANGUAGES C CXX ASM)

set(NSX_BOARD "{board}" CACHE STRING "Target board")

include(${{CMAKE_CURRENT_LIST_DIR}}/cmake/nsx/modules.cmake)
include(${{CMAKE_CURRENT_LIST_DIR}}/cmake/nsx/nsx_app_bootstrap.cmake)

nsx_bootstrap_app(
    APP_ROOT "${{CMAKE_CURRENT_LIST_DIR}}"
    BOARD "${{NSX_BOARD}}"
    MODULES ${{NSX_APP_MODULES}}
)

# --- heliaRT (engine module injected by heliaPROFILER) ---
add_subdirectory(
    "${{CMAKE_CURRENT_LIST_DIR}}/modules/nsx-heliart"
    "${{CMAKE_CURRENT_BINARY_DIR}}/_nsx/nsx_heliart"
)

# --- Profiler application ---
add_executable(hpx_profiler
    src/main.cc
    src/hpx_pmu_profiler.cc
)

target_include_directories(hpx_profiler PRIVATE
    ${{CMAKE_CURRENT_LIST_DIR}}/src
)

target_link_libraries(hpx_profiler PRIVATE
    nsx::board
    nsx::runtime_core
    nsx::power
    nsx::pmu_armv8m
    nsx::heliart
)

nsx_finalize_app(hpx_profiler)
"""

_MAIN_CC_TEMPLATE = """\
/**
 * @file main.cc
 * @brief heliaPROFILER firmware — auto-generated, do not edit.
 *
 * Runs inference with per-layer PMU profiling and emits CSV results
 * over SWO/UART for the host-side capture stage to parse.
 */

#include <cstdint>
#include <cstdio>
#include <cstring>

#include "{engine_header}"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/micro/tflite_bridge/micro_error_reporter.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "hpx_pmu_profiler.h"

extern "C" {{
#include "ns_core.h"
#include "ns_ambiqsuite_harness.h"
#include "nsx_mem.h"
#include "nsx_system.h"
}}

// DWT cycle counter
static inline void dwt_init(void) {{
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}}

// Model data (xxd-style include)
#include "model_data.h"

static constexpr int kArenaSize = {arena_size};
static constexpr int kMaxOps = 128;

NSX_MEM_FAST_BSS alignas(16) static uint8_t g_arena[kArenaSize];
static HpxPmuProfiler g_profiler;

// Register all common TFLM builtin ops for broad model compatibility.
static tflite::MicroMutableOpResolver<kMaxOps> &get_resolver() {{
    static tflite::MicroMutableOpResolver<kMaxOps> r;
    static bool init = false;
    if (!init) {{
        r.AddAbs();           r.AddAdd();
        r.AddAddN();          r.AddArgMax();
        r.AddArgMin();        r.AddAveragePool2D();
        r.AddBatchMatMul();   r.AddBatchToSpaceNd();
        r.AddBroadcastArgs(); r.AddBroadcastTo();
        r.AddCast();          r.AddCeil();
        r.AddConcatenation(); r.AddConv2D();
        r.AddCumSum();        r.AddDepthToSpace();
        r.AddDepthwiseConv2D(); r.AddDequantize();
        r.AddDiv();           r.AddElu();
        r.AddEmbeddingLookup(); r.AddEqual();
        r.AddExp();           r.AddExpandDims();
        r.AddFill();          r.AddFloor();
        r.AddFloorDiv();      r.AddFloorMod();
        r.AddFullyConnected(); r.AddGather();
        r.AddGatherNd();      r.AddGreater();
        r.AddGreaterEqual();  r.AddHardSwish();
        r.AddL2Normalization(); r.AddL2Pool2D();
        r.AddLeakyRelu();     r.AddLess();
        r.AddLessEqual();     r.AddLog();
        r.AddLogSoftmax();    r.AddLogicalAnd();
        r.AddLogicalNot();    r.AddLogicalOr();
        r.AddLogistic();      r.AddMaxPool2D();
        r.AddMaximum();       r.AddMean();
        r.AddMinimum();       r.AddMirrorPad();
        r.AddMul();           r.AddNeg();
        r.AddNotEqual();      r.AddPack();
        r.AddPad();           r.AddPadV2();
        r.AddPrelu();         r.AddQuantize();
        r.AddReduceMax();     r.AddRelu();
        r.AddRelu6();         r.AddReshape();
        r.AddResizeBilinear(); r.AddResizeNearestNeighbor();
        r.AddRound();         r.AddRsqrt();
        r.AddSelectV2();      r.AddShape();
        r.AddSlice();         r.AddSoftmax();
        r.AddSpaceToBatchNd(); r.AddSpaceToDepth();
        r.AddSplit();         r.AddSplitV();
        r.AddSqrt();          r.AddSquare();
        r.AddSquaredDifference(); r.AddSqueeze();
        r.AddStridedSlice();  r.AddSub();
        r.AddSum();           r.AddSvdf();
        r.AddTanh();          r.AddTranspose();
        r.AddTransposeConv(); r.AddUnidirectionalSequenceLSTM();
        r.AddUnpack();        r.AddZerosLike();
        init = true;
    }}
    return r;
}}

int main(void) {{
    nsx_system_config_t sys_cfg = nsx_system_development;
    sys_cfg.skip_bsp_init = true;
    NS_TRY(nsx_system_init(&sys_cfg), "System init failed\\n");
    dwt_init();

    ns_printf("\\n--- HPX_START ---\\n");
    ns_printf("HPX_MODEL_SIZE=%u\\n", model_data_len);
    ns_printf("HPX_ARENA_SIZE=%d\\n", kArenaSize);
    ns_printf("HPX_ITERATIONS={iterations}\\n");
    ns_printf("HPX_WARMUP={warmup}\\n");

    tflite::InitializeTarget();

    const tflite::Model *model = tflite::GetModel(model_data);
    if (model->version() != TFLITE_SCHEMA_VERSION) {{
        ns_printf("HPX_ERROR=schema_mismatch:%lu_vs_%d\\n",
                  model->version(), TFLITE_SCHEMA_VERSION);
        while (1) {{}}
    }}

    g_profiler.Init({pmu_preset});

    auto &resolver = get_resolver();
    tflite::MicroInterpreter interpreter(model, resolver, g_arena, kArenaSize,
                                         nullptr, &g_profiler);
    if (interpreter.AllocateTensors() != kTfLiteOk) {{
        ns_printf("HPX_ERROR=alloc_tensors_failed\\n");
        while (1) {{}}
    }}

    TfLiteTensor *input = interpreter.input(0);
    ns_printf("HPX_INPUT_SIZE=%d\\n", (int)input->bytes);
    ns_printf("HPX_ALLOCATED_ARENA=%zu\\n", interpreter.arena_used_bytes());

    // Warmup iterations (profiler disabled)
    for (int w = 0; w < {warmup}; w++) {{
        memset(input->data.raw, 0, input->bytes);
        interpreter.Invoke();
    }}

    // Profiled iterations
    for (int iter = 0; iter < {iterations}; iter++) {{
        memset(input->data.raw, 0, input->bytes);
        g_profiler.ClearEvents();
        interpreter.Invoke();

        ns_printf("\\n--- HPX_ITER %d ---\\n", iter);
        g_profiler.PrintCsv();
    }}

    ns_printf("\\n--- HPX_END ---\\n");
    while (1) {{}}
    return 0;
}}
"""

_PMU_PROFILER_H = """\
#ifndef HPX_PMU_PROFILER_H
#define HPX_PMU_PROFILER_H

#include "tensorflow/lite/micro/micro_profiler_interface.h"

extern "C" {
#include "ns_pmu_utils.h"
}

class HpxPmuProfiler : public tflite::MicroProfilerInterface {
 public:
    static constexpr int kMaxLayers = 512;
    static constexpr int kNumEvents = 4;

    HpxPmuProfiler() = default;
    ~HpxPmuProfiler() override = default;

    void Init(ns_pmu_preset_e preset = NS_PMU_PRESET_ML_DEFAULT);

    uint32_t BeginEvent(const char* tag) override;
    void EndEvent(uint32_t event_handle) override;

    void ClearEvents();
    void PrintCsv() const;
    int num_events() const { return num_events_; }

 private:
    struct LayerRecord {
        const char* tag;
        uint32_t counters[kNumEvents];
    };
    ns_pmu_config_t pmu_cfg_ = {};
    LayerRecord layers_[kMaxLayers] = {};
    int num_events_ = 0;
    bool initialized_ = false;
};

#endif  // HPX_PMU_PROFILER_H
"""

_PMU_PROFILER_CC = """\
#include "hpx_pmu_profiler.h"

extern "C" {
#include "ns_ambiqsuite_harness.h"
#include "ns_pmu_map.h"
}

void HpxPmuProfiler::Init(ns_pmu_preset_e preset) {
    ns_pmu_reset_config(&pmu_cfg_);
    pmu_cfg_.api = &ns_pmu_V1_0_0;
    ns_pmu_apply_preset(&pmu_cfg_, preset);
    ns_pmu_init(&pmu_cfg_);
    num_events_ = 0;
    initialized_ = true;
}

uint32_t HpxPmuProfiler::BeginEvent(const char* tag) {
    if (!initialized_ || num_events_ >= kMaxLayers) return 0;
    int idx = num_events_++;
    layers_[idx].tag = tag;
    uint32_t saved_cyccnt = DWT->CYCCNT;
    ns_pmu_reset_counters();
    DWT->CYCCNT = saved_cyccnt;
    return static_cast<uint32_t>(idx);
}

void HpxPmuProfiler::EndEvent(uint32_t event_handle) {
    if (!initialized_ ||
        event_handle >= static_cast<uint32_t>(num_events_)) return;
    uint32_t saved_cyccnt = DWT->CYCCNT;
    ns_pmu_get_counters(&pmu_cfg_);
    DWT->CYCCNT = saved_cyccnt;
    LayerRecord& rec = layers_[event_handle];
    for (int i = 0; i < kNumEvents; i++) {
        rec.counters[i] = pmu_cfg_.counter[i].counterValue;
    }
}

void HpxPmuProfiler::ClearEvents() { num_events_ = 0; }

void HpxPmuProfiler::PrintCsv() const {
    if (!initialized_ || num_events_ == 0) return;
    ns_printf("\\"Layer\\",\\"Op\\"");
    for (int e = 0; e < kNumEvents; e++) {
        if (!pmu_cfg_.events[e].enabled) break;
        uint32_t map_idx = pmu_cfg_.counter[e].mapIndex;
        if (map_idx < NS_PMU_MAP_SIZE)
            ns_printf(",\\"%s\\"", ns_pmu_map[map_idx].regname);
        else
            ns_printf(",\\"event_%d\\"", e);
    }
    ns_printf("\\n");
    for (int i = 0; i < num_events_; i++) {
        const LayerRecord& rec = layers_[i];
        ns_printf("%d,%s", i, rec.tag ? rec.tag : "?");
        for (int e = 0; e < kNumEvents; e++) {
            if (!pmu_cfg_.events[e].enabled) break;
            ns_printf(",%lu", (unsigned long)rec.counters[e]);
        }
        ns_printf("\\n");
    }
}
"""


def _model_to_header(model_path: Path) -> str:
    """Convert a .tflite model to a C header (xxd-style byte array)."""
    data = model_path.read_bytes()
    lines = [
        "// Auto-generated by heliaPROFILER — do not edit.",
        f"// Source: {model_path.name}",
        "alignas(16) static const unsigned char model_data[] = {",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    lines.append(f"static const unsigned int model_data_len = {len(data)};")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_app(ctx: PipelineContext) -> Path:
    """Render firmware templates into an NSX-compatible profiler app.

    Returns the path to the generated app directory inside ``ctx.work_dir``.
    """
    assert ctx.soc is not None
    assert ctx.board is not None
    assert ctx.engine_artifacts is not None

    app_dir = ctx.work_dir / "profiler_app"
    app_dir.mkdir(parents=True, exist_ok=True)

    config = ctx.config
    soc = ctx.soc
    board = ctx.board
    artifacts = ctx.engine_artifacts
    tvars = artifacts.template_vars

    # --- Resolve module list ---
    modules = _resolve_module_list(board.name, soc.sdk_tier)
    log.info("NSX modules: %s", ", ".join(modules))

    # --- nsx.yml ---
    module_entries = "\n".join(f"- name: {m}\n  revision: main\n  project: {m}" for m in modules)
    nsx_yml = _NSX_YML_TEMPLATE.format(
        board=board.name,
        soc=soc.name,
        toolchain=config.target.toolchain,
        module_entries=module_entries,
    )
    (app_dir / "nsx.yml").write_text(nsx_yml)

    # --- cmake/nsx/modules.cmake ---
    cmake_nsx_dir = app_dir / "cmake" / "nsx"
    cmake_nsx_dir.mkdir(parents=True, exist_ok=True)
    module_list = "\n".join(f"    {m}" for m in modules)
    (cmake_nsx_dir / "modules.cmake").write_text(
        _MODULES_CMAKE_TEMPLATE.format(module_list=module_list)
    )

    # --- CMakeLists.txt ---
    (app_dir / "CMakeLists.txt").write_text(_CMAKELISTS_TEMPLATE.format(board=board.name))

    # --- Source files ---
    src_dir = app_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Model data header
    model_header = _model_to_header(config.model.path)
    (src_dir / "model_data.h").write_text(model_header)

    # PMU preset
    first_preset = config.profiling.pmu_presets[0] if config.profiling.pmu_presets else "ml_default"
    pmu_preset_c = _PMU_PRESET_MAP.get(first_preset, "NS_PMU_PRESET_ML_DEFAULT")

    # Arena size: use configured value or default 256KB
    arena_size = config.model.arena_size or (256 * 1024)

    # main.cc
    engine_header = tvars.get("engine_header", "tensorflow/lite/micro/micro_interpreter.h")
    (src_dir / "main.cc").write_text(
        _MAIN_CC_TEMPLATE.format(
            engine_header=engine_header,
            arena_size=arena_size,
            iterations=config.profiling.iterations,
            warmup=config.profiling.warmup,
            pmu_preset=pmu_preset_c,
        )
    )

    # PMU profiler
    (src_dir / "hpx_pmu_profiler.h").write_text(_PMU_PROFILER_H)
    (src_dir / "hpx_pmu_profiler.cc").write_text(_PMU_PROFILER_CC)

    # --- Engine wrapper module ---
    for extra_mod in artifacts.extra_modules:
        mod_name = extra_mod["name"]
        mod_src = Path(extra_mod["path"])
        mod_dst = app_dir / "modules" / mod_name
        if mod_src != mod_dst:
            if mod_dst.exists():
                shutil.rmtree(mod_dst)
            shutil.copytree(mod_src, mod_dst)
        log.info("Engine module: %s → %s", mod_name, mod_dst)

    log.info("Generated profiler app at %s", app_dir)
    return app_dir


def build_app(ctx: PipelineContext) -> tuple[Path, Path]:
    """Invoke ``nsx configure`` + ``nsx build`` on the generated app.

    Returns (build_dir, binary_path).
    """
    assert ctx.firmware_dir is not None
    assert ctx.board is not None

    app_dir = ctx.firmware_dir
    board = ctx.board.name

    # --- nsx configure ---
    log.info("Running: nsx configure --app-dir %s", app_dir)
    try:
        result = subprocess.run(
            ["nsx", "configure", "--app-dir", str(app_dir)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise BuildError(
            "nsx CLI not found",
            hint="Install neuralspotx: pip install neuralspotx  (or ensure 'nsx' is in PATH)",
        )
    if result.returncode != 0:
        raise BuildError(
            "nsx configure failed",
            returncode=result.returncode,
            stderr=result.stderr,
        )
    log.info("Configure stdout:\n%s", result.stdout)

    # --- nsx build ---
    log.info("Running: nsx build --app-dir %s", app_dir)
    try:
        result = subprocess.run(
            ["nsx", "build", "--app-dir", str(app_dir)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise BuildError(
            "nsx CLI not found",
            hint="Install neuralspotx: pip install neuralspotx  (or ensure 'nsx' is in PATH)",
        )
    if result.returncode != 0:
        raise BuildError(
            "nsx build failed",
            returncode=result.returncode,
            stderr=result.stderr,
        )
    log.info("Build stdout:\n%s", result.stdout)

    # Locate build output
    build_dir = app_dir / "build" / board
    bin_patterns = [
        str(build_dir / "hpx_profiler.bin"),
        str(build_dir / "**" / "hpx_profiler.bin"),
    ]
    binary_path = None
    for pattern in bin_patterns:
        matches = glob.glob(pattern, recursive=True)
        if matches:
            binary_path = Path(matches[0])
            break

    if binary_path is None:
        # Try .axf as fallback
        axf_matches = glob.glob(str(build_dir / "**" / "hpx_profiler.axf"), recursive=True)
        if axf_matches:
            binary_path = Path(axf_matches[0])

    if binary_path is None:
        raise BuildError(
            "Build succeeded but binary not found",
            hint=f"Searched in {build_dir}",
        )

    log.info("Binary: %s", binary_path)
    return build_dir, binary_path


def flash_app(ctx: PipelineContext) -> None:
    """Invoke ``nsx flash`` to deploy the binary to the target."""
    assert ctx.firmware_dir is not None

    app_dir = ctx.firmware_dir

    log.info("Running: nsx flash --app-dir %s", app_dir)
    try:
        result = subprocess.run(
            ["nsx", "flash", "--app-dir", str(app_dir)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise BuildError(
            "nsx CLI not found",
            hint="Install neuralspotx: pip install neuralspotx  (or ensure 'nsx' is in PATH)",
        )
    if result.returncode != 0:
        raise BuildError(
            "nsx flash failed",
            returncode=result.returncode,
            stderr=result.stderr,
        )
    log.info("Flash complete.")
