"""Generated C headers — model byte arrays and constant sidecar blobs.

Owns the xxd-style header generation embedded into generated apps: the
``.tflite`` model array with its placement-driven section attribute, and the
AOT constant-arena sidecar blob arrays.  Extracted from ``firmware/__init__``
at the module size ceiling (see the elf_inventory precedent in
toolchain_probe); the package re-exports every name so callers keep one
import surface.
"""

from __future__ import annotations

from pathlib import Path


def _model_to_header(model_path: Path, weights_region: str = "mram") -> str:
    """Convert a .tflite model to a C header (xxd-style byte array).

    ``weights_region`` selects the section attribute applied to
    ``model_data[]``:

    * ``mram`` (default) — ``static const`` (rodata, stays in flash/MRAM).
    * ``tcm`` — ``NSX_MEM_FAST static`` (loaded into DTCM at boot).
    * ``sram`` — ``NSX_MEM_SRAM static`` (loaded into shared SRAM at boot).

    For TCM/SRAM placement we drop ``const`` because NSX initialises these
    sections by copying from NVM at boot, which requires writable storage.
    """
    data = model_path.read_bytes()

    if weights_region == "tcm":
        decl = "NSX_MEM_FAST alignas(16) static unsigned char model_data[] = {"
        include_nsx = True
    elif weights_region == "sram":
        decl = "NSX_MEM_SRAM alignas(16) static unsigned char model_data[] = {"
        include_nsx = True
    else:  # mram / default
        decl = "alignas(16) static const unsigned char model_data[] = {"
        include_nsx = False

    lines = [
        "// Auto-generated by heliaPROFILER — do not edit.",
        f"// Source: {model_path.name}",
        f"// Placement: {weights_region}",
    ]
    if include_nsx:
        lines.append('#include "nsx_mem.h"')
    lines.append(decl)
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    if weights_region in ("tcm", "sram"):
        lines.append(f"static unsigned int model_data_len = {len(data)};")
    else:
        lines.append(f"static const unsigned int model_data_len = {len(data)};")
    return "\n".join(lines) + "\n"


def _blob_to_header(blob_path: Path, symbol_name: str) -> str:
    """Convert a sidecar constant blob to a C header (xxd-style byte array).

    The blob is placed in ``.rodata`` (const, stays in flash/MRAM) so it
    can be memcpy'd into the runtime arena buffer at boot.
    """
    data = blob_path.read_bytes()
    lines = [
        "// Auto-generated by heliaPROFILER — do not edit.",
        f"// Constant arena sidecar blob: {blob_path.name}",
        "#pragma once",
        "#include <stddef.h>",
        f"alignas(16) static const unsigned char {symbol_name}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    lines.append(f"static const size_t {symbol_name}_len = sizeof({symbol_name});")
    return "\n".join(lines) + "\n"
