"""heliaRT engine adapter.

Generates a local NSX wrapper module for heliaRT prebuilt static libraries.
The wrapper is a temporary shim until heliaRT ships a native nsx-module.yaml.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from ..config import ProfileConfig
from ..errors import EngineError
from ..platform import CoreArch, get_soc
from .base import EngineArtifacts

log = logging.getLogger("hpx")

# ---------------------------------------------------------------------------
# Pinned heliaRT release — bump this when a new release is adopted.
# ---------------------------------------------------------------------------
HELIART_VERSION = "1.7.0"
HELIART_GH_REPO = "AmbiqAI/helia-rt"
HELIART_RELEASE_TAG = f"v{HELIART_VERSION}"
HELIART_ASSET_PREFIX = f"nsx-heliart-{HELIART_RELEASE_TAG}"

# ---------------------------------------------------------------------------
# NSX module wrapper templates
# ---------------------------------------------------------------------------

_NSX_MODULE_YAML = """\
# Auto-generated by heliaPROFILER — do not edit.
# This wrapper makes a heliaRT prebuilt release look like an NSX module.
schema_version: 1

module:
  name: nsx-heliart
  type: backend_specific
  version: "{version}"

support:
  ambiqsuite: true
  zephyr: false

summary: >-
  heliaRT {version} — Ambiq optimized LiteRT inference runtime (prebuilt).
  Auto-generated NSX wrapper by heliaPROFILER.

build:
  cmake:
    package: nsx_heliart
    targets:
      - nsx::heliart

depends:
  required:
    - nsx-core
    - nsx-soc-hal
  optional: []

compatibility:
  boards: ["*"]
  socs:
    - apollo3p
    - apollo4p
    - apollo4l
    - apollo510
    - apollo510b
    - apollo5b
    - apollo330P
  toolchains:
    - arm-none-eabi-gcc
"""

_CMAKELISTS_TXT = """\
# Auto-generated by heliaPROFILER — do not edit.
# NSX wrapper for heliaRT {version} prebuilt static library.

if(NOT DEFINED NSX_BOARD_FLAGS_TARGET)
    message(FATAL_ERROR "Board must define NSX_BOARD_FLAGS_TARGET before nsx-heliart.")
endif()
if(NOT DEFINED NSX_SOC_FAMILY)
    message(FATAL_ERROR "NSX_SOC_FAMILY must be defined before nsx-heliart.")
endif()

# --- Resolve core from SoC family ---
set(_HELIART_CORE "")
if(NSX_SOC_FAMILY MATCHES "^apollo5|^apollo330|^apollo510")
    set(_HELIART_CORE "cm55")
elseif(NSX_SOC_FAMILY MATCHES "^apollo4|^apollo3")
    set(_HELIART_CORE "cm4")
else()
    message(FATAL_ERROR "nsx-heliart: unsupported NSX_SOC_FAMILY '${{NSX_SOC_FAMILY}}'")
endif()

# --- Build variant ---
set(HELIART_VARIANT "{variant}" CACHE STRING
    "heliaRT build variant: debug | release-with-logs | release")

# --- Locate prebuilt library ---
set(_HELIART_LIB_NAME
    "libtensorflow-microlite-${{_HELIART_CORE}}-gcc-${{HELIART_VARIANT}}.a")
set(_HELIART_LIB_PATH
    "${{CMAKE_CURRENT_LIST_DIR}}/lib/${{_HELIART_LIB_NAME}}")

if(NOT EXISTS "${{_HELIART_LIB_PATH}}")
    message(FATAL_ERROR
        "nsx-heliart: prebuilt library not found:\\n"
        "  ${{_HELIART_LIB_PATH}}\\n"
        "Expected heliaRT {version} release artifacts in lib/.")
endif()

message(STATUS "nsx-heliart: ${{_HELIART_LIB_NAME}}")

# --- Import prebuilt static library ---
add_library(nsx_heliart_prebuilt STATIC IMPORTED GLOBAL)
set_target_properties(nsx_heliart_prebuilt PROPERTIES
    IMPORTED_LOCATION "${{_HELIART_LIB_PATH}}"
)

# --- Platform glue (must be compiled against target HAL) ---
add_library(nsx_heliart STATIC
    ${{CMAKE_CURRENT_LIST_DIR}}/tensorflow/lite/micro/micro_log.cc
    ${{CMAKE_CURRENT_LIST_DIR}}/tensorflow/lite/micro/cortex_m_generic/debug_log.cc
)
set_target_properties(nsx_heliart PROPERTIES EXPORT_NAME heliart)
add_library(nsx::heliart ALIAS nsx_heliart)

target_link_libraries(nsx_heliart
    PUBLIC
        ${{NSX_BOARD_FLAGS_TARGET}}
        nsx_heliart_prebuilt
    PRIVATE
        nsx_soc_hal
        nsx_core
)

target_include_directories(nsx_heliart PUBLIC
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}>
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party>
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party/flatbuffers/include>
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/third_party/gemmlowp>
)

target_compile_definitions(nsx_heliart PUBLIC
    TF_LITE_STATIC_MEMORY
    NS_TFSTRUCTURE_RECENT
    NS_TFLM_NEW_MICRO_PROFILER
)

install(TARGETS nsx_heliart EXPORT nsxTargets)
"""


def _core_tag(board: str) -> str:
    """Map a board name to the heliaRT library core tag (cm4 or cm55)."""
    soc = get_soc(_board_to_soc(board))
    if soc.core is CoreArch.CORTEX_M55:
        return "cm55"
    return "cm4"


def _board_to_soc(board: str) -> str:
    """Resolve board name to SoC name via the platform registry."""
    from ..platform import get_board

    return get_board(board).soc


class HeliaRTAdapter:
    """Adapter for heliaRT — Ambiq's optimized TFLM fork.

    Generates a local NSX wrapper module that makes a pinned heliaRT release
    appear as ``nsx::heliart`` to the profiler firmware's CMake build.  The
    wrapper is placed inside ``work_dir/modules/nsx-heliart/``.

    Once heliaRT ships a native ``nsx-module.yaml``, this adapter can simply
    declare a module dependency and skip wrapper generation entirely.
    """

    @property
    def name(self) -> str:
        return "heliaRT"

    def prepare(self, config: ProfileConfig, work_dir: Path) -> EngineArtifacts:
        backend = config.engine.backend or "helia"
        variant = config.engine.config.get("variant", "release-with-logs")

        # Validate variant
        valid_variants = ("debug", "release-with-logs", "release")
        if variant not in valid_variants:
            raise EngineError(
                f"Invalid heliaRT variant '{variant}'",
                hint=f"Valid variants: {', '.join(valid_variants)}",
            )

        # Resolve the heliaRT distribution path
        dist_path = _resolve_dist_path(config)

        # Generate the NSX wrapper module
        module_dir = work_dir / "modules" / "nsx-heliart"
        module_dir.mkdir(parents=True, exist_ok=True)

        _write_wrapper(module_dir, variant=variant)
        _link_distribution(module_dir, dist_path)

        log.info(
            "Generated NSX wrapper for heliaRT %s (variant=%s, dist=%s)",
            HELIART_VERSION,
            variant,
            dist_path,
        )

        return EngineArtifacts(
            extra_modules=[
                {
                    "name": "nsx-heliart",
                    "path": str(module_dir),
                    "version": HELIART_VERSION,
                },
            ],
            template_vars={
                "engine_type": "helia_rt",
                "engine_backend": backend,
                "engine_header": "tensorflow/lite/micro/micro_interpreter.h",
                "heliart_version": HELIART_VERSION,
                "heliart_variant": variant,
            },
        )


def _write_wrapper(module_dir: Path, *, variant: str) -> None:
    """Write the NSX wrapper files into *module_dir*."""
    (module_dir / "nsx-module.yaml").write_text(
        _NSX_MODULE_YAML.format(version=HELIART_VERSION),
    )
    (module_dir / "CMakeLists.txt").write_text(
        _CMAKELISTS_TXT.format(version=HELIART_VERSION, variant=variant),
    )


# ---------------------------------------------------------------------------
# heliaRT distribution resolution
# ---------------------------------------------------------------------------

# Directories from the heliaRT release that must be present in the wrapper.
_DIST_DIRS = ("lib", "tensorflow", "third_party")


def _resolve_dist_path(config: ProfileConfig) -> Path:
    """Resolve the heliaRT distribution directory.

    Checks (in order):
    1. ``engine.config.dist_path`` — explicit user-provided path
    2. ``HELIART_DIST_PATH`` environment variable
    3. Raise an error with helpful guidance.
    """
    # 1. Explicit config
    raw = config.engine.config.get("dist_path")
    if raw:
        p = Path(raw).expanduser().resolve()
        _validate_dist(p)
        return p

    # 2. Environment variable
    env = os.environ.get("HELIART_DIST_PATH")
    if env:
        p = Path(env).expanduser().resolve()
        _validate_dist(p)
        return p

    raise EngineError(
        "heliaRT distribution path not provided",
        hint=(
            "Set engine.config.dist_path in your config YAML, "
            "or export HELIART_DIST_PATH to the directory containing "
            f"the heliaRT {HELIART_VERSION} release (lib/, tensorflow/, third_party/)."
        ),
    )


def _validate_dist(dist: Path) -> None:
    """Verify that *dist* looks like a heliaRT release directory."""
    if not dist.is_dir():
        raise EngineError(
            f"heliaRT dist path does not exist: {dist}",
            hint="Provide a valid directory containing the heliaRT release.",
        )
    for d in _DIST_DIRS:
        if not (dist / d).is_dir():
            raise EngineError(
                f"heliaRT dist missing '{d}/' directory: {dist}",
                hint=f"Expected: {', '.join(d + '/' for d in _DIST_DIRS)}",
            )


def _link_distribution(module_dir: Path, dist_path: Path) -> None:
    """Symlink heliaRT distribution directories into the wrapper module.

    Creates symlinks for lib/, tensorflow/, and third_party/ so the CMake
    build can find them via ``CMAKE_CURRENT_LIST_DIR``.
    """
    for d in _DIST_DIRS:
        target = module_dir / d
        source = dist_path / d
        if target.is_symlink():
            target.unlink()
        elif target.is_dir():
            # Real directory from a prior run — remove it
            import shutil

            shutil.rmtree(target)
        target.symlink_to(source, target_is_directory=True)
        log.debug("Linked %s → %s", target, source)
