model:
  path: examples/models/resnet8_random_int8.tflite
  arena_size: 262144
  weights_location: mram
  arena_location: tcm

engine:
  type: helia-rt

target:
  board: apollo510_evb
  toolchain: arm-none-eabi-gcc
  jlink_serial: "1160003180"
  transport: rtt
  clock:
    cpu: lp

profiling:
  pmu_counters:
    cpu: default
    mve: default
    memory: default
  per_layer: true
  iterations: 25
  warmup: 5
  aggregation: median

power:
  enabled: false

output:
  format: json
  dir: ./results/resnet8_random/helia_rt
  model_explorer: false
  detailed: true
