"""Specs for the error and warning catalogues."""

from __future__ import annotations

from ..engines import EngineType
from ._model import (
    AOT_ENGINES,
    ET_ENGINES,
    GATE_AOT_CONST_BLOBS_IN_PSRAM,
    GATE_AOT_EXTERNAL_ARENAS,
    GATE_AOT_PSRAM_ARENAS,
    GATE_NOT_POWER_ONLY,
    GATE_PSRAM_NEEDED,
    TFLM_ENGINES,
    FirmwareErrorCode,
    FirmwareWarnCode,
    WireConsumer,
    WireCriticality,
    WireKind,
    WireSpec,
    _spec,
    error_token,
    warn_token,
)

ERROR_SPECS: tuple[WireSpec, ...] = (
    _spec(
        error_token(FirmwareErrorCode.SCHEMA_MISMATCH),
        WireKind.ERROR,
        "The model's TFLite schema version is not the one firmware was built "
        "for.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES,
        value_shape="schema_mismatch:<found>_vs_<expected>",
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.UNSUPPORTED_OP),
        WireKind.ERROR,
        "An operator in the model is not registered in the resolver.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES,
        value_shape="kind=custom|builtin [builtin=<n>] name=<s> index=<n>",
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.MISSING_OPS),
        WireKind.ERROR,
        "Summary count of unregistered operators after the preflight walk.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES,
        value_shape="count=<n> hint=rebuild_with_op_registration",
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.ALLOC_TENSORS_FAILED),
        WireKind.ERROR,
        "TFLM AllocateTensors() failed.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES,
        value_shape="arena=<bytes> status=<n> hint=<s>",
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.PSRAM_INIT_FAILED),
        WireKind.ERROR,
        "PSRAM bring-up failed on the target.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES | AOT_ENGINES,
        condition=GATE_PSRAM_NEEDED,
        engine_conditions={EngineType.HELIA_AOT: GATE_AOT_PSRAM_ARENAS},
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.PSRAM_INFO_FAILED),
        WireKind.ERROR,
        "PSRAM came up but its info query failed.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=TFLM_ENGINES | AOT_ENGINES,
        condition=GATE_PSRAM_NEEDED,
        engine_conditions={EngineType.HELIA_AOT: GATE_AOT_PSRAM_ARENAS},
    ),
    _spec(
        error_token(FirmwareErrorCode.BIND_ARENA_FAILED),
        WireKind.ERROR,
        "Binding one external arena region to the heliaAOT model failed.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=AOT_ENGINES,
        condition=GATE_AOT_EXTERNAL_ARENAS,
        value_shape="bind_arena_failed:<status>:region=<id>",
    ),
    _spec(
        error_token(FirmwareErrorCode.CONST_BLOB_PSRAM_WRITE_FAILED),
        WireKind.ERROR,
        "Writing a constant sidecar blob into PSRAM failed.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=AOT_ENGINES,
        condition=GATE_AOT_CONST_BLOBS_IN_PSRAM,
        value_shape="const_blob_psram_write_failed:region=<id>",
    ),
    _spec(
        error_token(FirmwareErrorCode.MODEL_INIT_FAILED),
        WireKind.ERROR,
        "heliaAOT model_init() returned a non-zero status.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=AOT_ENGINES,
        value_shape="model_init_failed:<status>",
        has_host_hint=True,
    ),
    _spec(
        error_token(FirmwareErrorCode.EXECUTORCH),
        WireKind.ERROR,
        "An ExecuTorch runtime call failed; the stage names which one.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=ET_ENGINES,
        value_shape="stage=<s> error=<n> planned=<n>",
        note="Single code for every ExecuTorch failure site.",
    ),
    _spec(
        error_token(FirmwareErrorCode.OPERATOR_COUNT_EXCEEDS_CAPACITY),
        WireKind.ERROR,
        "The model has more operators than the per-layer record array holds.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=ET_ENGINES,
        condition=GATE_NOT_POWER_ONLY,
        value_shape="capacity=<n>",
        runtime_gate="the capacity was actually exceeded during the pass",
        note="Printed just before the CSV body, so the rows that follow are "
        "truncated rather than absent.",
    ),
    _spec(
        error_token(FirmwareErrorCode.PMU_INIT_OR_SELFTEST_FAILED),
        WireKind.ERROR,
        "PMU init or its cycle-counter self-test failed for this pass.",
        WireConsumer.TRANSPORT_CONTROL,
        WireCriticality.PROTOCOL,
        engines=ET_ENGINES,
        condition=GATE_NOT_POWER_ONLY,
        value_shape="pass=<name>",
    ),
)


WARN_SPECS: tuple[WireSpec, ...] = (
    _spec(
        warn_token(FirmwareWarnCode.UNUSUAL_DTYPE),
        WireKind.WARN,
        "A tensor has a dtype the preflight walk did not expect.",
        WireConsumer.UNCONSUMED,
        WireCriticality.DIAGNOSTIC,
        engines=TFLM_ENGINES,
        value_shape="tensor=<n> dtype=<n> name=<s>",
        note="Non-fatal; the run continues. Nothing on the host reads it — "
        "only HPX_ERROR lines are scanned.",
    ),
)

