"""heliaPROFILER — Profile LiteRT and ExecuTorch models on Ambiq silicon"""

from . import examples
from ._version import __version__
from .api import profile
from .config import (
    BuildConfig,
    ClockSelection,
    EngineConfig,
    HeartbeatConfig,
    ModelConfig,
    NsxModuleOverride,
    OutputConfig,
    OutputFormat,
    PowerConfig,
    ProfileConfig,
    ProfilingConfig,
    TargetConfig,
    TimeoutsConfig,
    Toolchain,
    Transport,
)
from .deps.compatibility import (
    CompatibilityBaseline,
    CompatibilityResolution,
    QualificationState,
    load_compatibility_baseline,
)
from .deps.dependencies import read_dependency_lock_provenance
from .diagnostics.support_bundle import (
    SupportBundleOptions,
    collect_support_bundle,
    verify_support_bundle,
    write_support_bundle,
)
from .engines import EngineType
from .errors import (
    BuildError,
    CaptureError,
    ConfigError,
    DependencyError,
    DeterministicCaptureError,
    EngineError,
    FirmwareError,
    HpxError,
    LockError,
    NetworkError,
    PlatformError,
    PowerError,
    ReportError,
    VersionError,
)
from .evaluation import (
    ComparabilityAssessment,
    ComparabilityIssue,
    ComparabilitySeverity,
    CompareResult,
    ComparisonProfile,
    ComparisonVerdict,
    MetricDirection,
    MetricPolicy,
    MetricVerdict,
    MissingMetricPolicy,
    RunEvaluation,
    VerdictStatus,
    assess_comparability,
    evaluate_comparison_profile,
    evaluate_run,
)
from .hostenv.doctor import DoctorCheck, DoctorResult, DoctorVersionCheck
from .modelcost import ModelAnalysis
from .pipeline import ProgressUpdate
from .placement import Placement
from .platform import BoardDef, SocDef, build_platform_registry, get_soc
from .platform.counters import PmuCounter
from .power.base import PowerMode, PowerResult
from .power.metadata import (
    MeasurementScope,
    ObservationMode,
    PowerIntegrity,
    PowerMetadata,
)
from .results import (
    DependencyLockProvenance,
    FirmwareMeta,
    LayerResult,
    NsxModuleRef,
    OnDevicePowerSummary,
    PmuResult,
    PowerObservation,
    PowerTerminalRecord,
    PresetResult,
    ProfileResult,
    ResultArtifact,
    ResultIssue,
    ResultManifest,
    ResultValidity,
    RunMetadata,
    RunStatus,
    SupportBundleManifest,
    SupportBundleSection,
    load_result_manifest,
)
from .runtime_records import (
    Qualification,
    QualifiedTarget,
    RuntimeQualification,
    RuntimeRecord,
    RuntimeSource,
    qualification,
    runtimes,
)
from .session import Session
from .target.lifecycle import ResetStrategy
from .target.probe.jlink import JLinkProbe, JLinkProbeMatch
from .transport.ports import SerialPortInfo

__all__ = [
    "__version__",
    # Public API
    "profile",
    "Session",
    "ProgressUpdate",
    "examples",
    # Config
    "ProfileConfig",
    "CompatibilityBaseline",
    "CompatibilityResolution",
    "QualificationState",
    "load_compatibility_baseline",
    "Qualification",
    "QualifiedTarget",
    "RuntimeQualification",
    "RuntimeRecord",
    "RuntimeSource",
    "qualification",
    "runtimes",
    "ModelConfig",
    "EngineConfig",
    "EngineType",
    "TargetConfig",
    "ProfilingConfig",
    "PowerConfig",
    "OutputConfig",
    "Toolchain",
    "Transport",
    "ClockSelection",
    "OutputFormat",
    "HeartbeatConfig",
    "TimeoutsConfig",
    "BuildConfig",
    "NsxModuleOverride",
    "Placement",
    "PowerMode",
    "PowerResult",
    "MeasurementScope",
    "ObservationMode",
    "PowerIntegrity",
    "PowerMetadata",
    "PowerObservation",
    "PowerTerminalRecord",
    "OnDevicePowerSummary",
    "ResetStrategy",
    # Results
    "ProfileResult",
    "PmuResult",
    "PresetResult",
    "LayerResult",
    "FirmwareMeta",
    "RunMetadata",
    "NsxModuleRef",
    "ModelAnalysis",
    "CompareResult",
    "ComparabilityAssessment",
    "ComparabilityIssue",
    "ComparabilitySeverity",
    "assess_comparability",
    "ComparisonProfile",
    "ComparisonVerdict",
    "MetricDirection",
    "MetricPolicy",
    "MetricVerdict",
    "MissingMetricPolicy",
    "VerdictStatus",
    "evaluate_comparison_profile",
    "RunEvaluation",
    "evaluate_run",
    "ResultManifest",
    "ResultArtifact",
    "ResultIssue",
    "ResultValidity",
    "RunStatus",
    "load_result_manifest",
    "DependencyLockProvenance",
    "read_dependency_lock_provenance",
    "SupportBundleManifest",
    "SupportBundleSection",
    "SupportBundleOptions",
    "collect_support_bundle",
    "write_support_bundle",
    "verify_support_bundle",
    "DoctorCheck",
    "DoctorResult",
    "DoctorVersionCheck",
    "BoardDef",
    "SocDef",
    "build_platform_registry",
    "get_soc",
    "PmuCounter",
    "JLinkProbe",
    "JLinkProbeMatch",
    "SerialPortInfo",
    # Errors
    "HpxError",
    "ConfigError",
    "DependencyError",
    "VersionError",
    "LockError",
    "PlatformError",
    "EngineError",
    "FirmwareError",
    "BuildError",
    "NetworkError",
    "CaptureError",
    "DeterministicCaptureError",
    "PowerError",
    "ReportError",
]

_STABLE_API = {
    "__version__",
    "profile",
    "Session",
    "ProgressUpdate",
    "examples",
    "ProfileConfig",
    "CompatibilityBaseline",
    "CompatibilityResolution",
    "QualificationState",
    "load_compatibility_baseline",
    "ModelConfig",
    "EngineConfig",
    "EngineType",
    "TargetConfig",
    "ProfilingConfig",
    "PowerConfig",
    "OutputConfig",
    "Toolchain",
    "Transport",
    "ClockSelection",
    "OutputFormat",
    "HeartbeatConfig",
    "TimeoutsConfig",
    "BuildConfig",
    "Placement",
    "PowerMode",
    "ResetStrategy",
    "ProfileResult",
    "PmuResult",
    "PresetResult",
    "LayerResult",
    "FirmwareMeta",
    "RunMetadata",
    "PowerResult",
    "HpxError",
    "ConfigError",
    "PlatformError",
    "EngineError",
    "FirmwareError",
    "BuildError",
    "NetworkError",
    "CaptureError",
    "DeterministicCaptureError",
    "PowerError",
    "ReportError",
}

_EXPERIMENTAL_API = {
    "Qualification",
    "QualifiedTarget",
    "RuntimeQualification",
    "RuntimeRecord",
    "RuntimeSource",
    "qualification",
    "runtimes",
    "MeasurementScope",
    "ObservationMode",
    "PowerIntegrity",
    "PowerMetadata",
    "PowerObservation",
    "PowerTerminalRecord",
    "OnDevicePowerSummary",
    "ModelAnalysis",
    "CompareResult",
    "ComparabilityAssessment",
    "ComparabilityIssue",
    "ComparabilitySeverity",
    "assess_comparability",
    "ComparisonProfile",
    "ComparisonVerdict",
    "MetricDirection",
    "MetricPolicy",
    "MetricVerdict",
    "MissingMetricPolicy",
    "VerdictStatus",
    "evaluate_comparison_profile",
    "RunEvaluation",
    "evaluate_run",
    "ResultManifest",
    "ResultArtifact",
    "ResultIssue",
    "ResultValidity",
    "RunStatus",
    "load_result_manifest",
    "DependencyLockProvenance",
    "read_dependency_lock_provenance",
    "DependencyError",
    "VersionError",
    "LockError",
    "SupportBundleManifest",
    "SupportBundleSection",
    "SupportBundleOptions",
    "collect_support_bundle",
    "write_support_bundle",
    "verify_support_bundle",
}

_IMPLEMENTATION_API = {
    "NsxModuleOverride",
    "NsxModuleRef",
    "DoctorCheck",
    "DoctorResult",
    "DoctorVersionCheck",
    "BoardDef",
    "SocDef",
    "build_platform_registry",
    "get_soc",
    "PmuCounter",
    "JLinkProbe",
    "JLinkProbeMatch",
    "SerialPortInfo",
}

__api_stability__ = {
    **{name: "stable" for name in _STABLE_API},
    **{name: "experimental" for name in _EXPERIMENTAL_API},
    **{name: "implementation" for name in _IMPLEMENTATION_API},
}
