"""heliaML NSX module resolution.

Two NSX modules go into a heliaML profiler build:

1. **heliaML itself.** heliaML ships ``nsx/nsx-module.yaml`` (module
   name ``helia-ml``, target ``nsx::helia_ml``) but no self-sufficient
   build entry -- the alias is defined by the repo root's CMakeLists.
   :func:`write_library_module_wrapper` therefore generates a thin
   wrapper that ``add_subdirectory()``s the checkout by ABSOLUTE path,
   the same pattern ``helia_rt/nsx_module.py`` uses for heliaRT's
   source-build mode (a copied module cannot carry a relative ``..``).
2. **The generated model module.** ``heliaml.export_module(...,
   integration="nsx")`` emits its own ``nsx-module.yaml`` (module name
   ``helia-ml-model``, target ``nsx::helia_ml_model``) alongside the
   model sources, so the model directory is passed to NSX as-is. Those
   names are a contract heliaML's own test suite asserts.
"""

from __future__ import annotations

from pathlib import Path

from ...errors import EngineError

#: NSX module names, as declared in the respective nsx-module.yaml files.
HELIAML_MODULE = "helia-ml"
HELIAML_MODEL_MODULE = "helia-ml-model"


def resolve_heliaml_root(config) -> Path:
    """Locate a heliaML checkout containing ``nsx/nsx-module.yaml``.

    Resolution order mirrors heliaRT's ``_resolve_source_path``: explicit
    engine config, then the ``HELIAML_ROOT`` environment variable.
    heliaML is not yet published, so there is no registry/PyPI fallback
    the way heliaRT has one.
    """
    import os

    root_cfg = config.engine.config.get("heliaml_root")
    root = Path(root_cfg) if root_cfg else None
    if root is None:
        env_root = os.environ.get("HELIAML_ROOT")
        root = Path(env_root) if env_root else None
    if root is None:
        raise EngineError(
            "heliaML checkout not found.",
            hint=(
                "Set engine.config.heliaml_root in the profile config, or "
                "export HELIAML_ROOT=/path/to/heliaml."
            ),
        )
    root = root.expanduser().resolve()
    module_yaml = root / "nsx" / "nsx-module.yaml"
    if not module_yaml.is_file():
        raise EngineError(
            f"HELIAML_ROOT does not look like a heliaML checkout: {root}",
            hint=f"Expected {module_yaml} to exist.",
        )
    return root


def write_library_module_wrapper(module_dir: Path, *, heliaml_root: Path) -> None:
    """Generate an NSX module wrapping the heliaML checkout itself.

    Copies the checkout's own ``nsx-module.yaml`` (the metadata is
    authoritative there) and adds the build entry the checkout does not
    ship: an ``add_subdirectory()`` of the repo root by absolute path,
    aliasing ``nsx::helia_ml``. Absolute, not relative -- hpx vendors
    module directories into the generated app, and a copied module
    cannot reach the checkout through ``..``.
    """
    module_dir.mkdir(parents=True, exist_ok=True)
    heliaml_root = heliaml_root.expanduser().resolve()

    (module_dir / "nsx-module.yaml").write_bytes(
        (heliaml_root / "nsx" / "nsx-module.yaml").read_bytes()
    )
    (module_dir / "CMakeLists.txt").write_text(
        "# Auto-generated by hpx HeliaMLAdapter.\n"
        "# Do not edit — regenerated on every hpx run.\n"
        "cmake_minimum_required(VERSION 3.21)\n"
        "\n"
        "if(NOT DEFINED NSX_BOARD_FLAGS_TARGET)\n"
        '    message(FATAL_ERROR\n'
        '        "helia-ml: NSX_BOARD_FLAGS_TARGET must be defined.")\n'
        "endif()\n"
        "\n"
        f'add_subdirectory("{heliaml_root.as_posix()}"\n'
        '    "${CMAKE_CURRENT_BINARY_DIR}/heliaml-src")\n'
        "# heliaML is board-agnostic C11 with no NSX dependency, so its own\n"
        "# CMakeLists carries no target flags. Link the board flags PUBLIC:\n"
        "# the generated model module links nsx::helia_ml PUBLIC and inherits\n"
        "# them transitively, keeping every TU on one arch/float ABI.\n"
        "target_link_libraries(heliaml PUBLIC ${NSX_BOARD_FLAGS_TARGET})\n"
        "if(NOT TARGET nsx::helia_ml)\n"
        "    add_library(nsx::helia_ml ALIAS heliaml)\n"
        "endif()\n"
    )
